framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options: 
                    exchange:
                        name: service_notification
                        # type: 'topic'
                        # passive: false
                        # durable: true
                        # auto_delete: false
                    queues:
                        notification_queue: 
                            binding_keys: ['entreprise.*','assurance.*']
                            # name: 'service_notification'
                            # durable: true
                            # auto_delete: false
                            # binding_keys:
                            #     - 'service_notification'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\NotificationMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
